# Generated by Django 4.1.6 on 2023-07-18 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/chef', verbose_name='Фото')),
                ('full_name', models.CharField(max_length=50, verbose_name='Фамилия, имя')),
                ('insta', models.CharField(max_length=50, verbose_name='Инстаграм')),
                ('twit', models.CharField(max_length=50, verbose_name='Твиттер')),
                ('face', models.CharField(max_length=50, verbose_name='Фейсбук')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.designation', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Повар',
                'verbose_name_plural': 'Повара',
            },
        ),
    ]
