# Generated by Django 4.1.6 on 2023-07-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='face',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фейсбук'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='insta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Инстаграм'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='twit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Твиттер'),
        ),
    ]
